name: Manual
on:
  workflow_dispatch:                      # 手動実行イベント
  inputs:
    greeting:
      type: string
      default: Hello
      required: true
      description: A cheerful word
jobs:
  run:
  steps:
    - run: echo "${{ inputs.greeting }}" # 入力パラメータ「greeting」の参照